server:
  port: 8080

spring:
  application:
    name: mybatis-demo
  datasource:
    url: jdbc:mysql://localhost:3306/shane
    username: root
    password: mysql2023
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    #    host: 192.168.31.49
    host: 106.14.216.125
    port: 6379
    #    password: 123456
    #    jedis:
    #      pool:
    #        min-idle: 0
    #        max-active: 8
    #        max-idle: 8
    #        max-wait: -1ms
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms
  messages:
    basename: messages/validation
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.shane.mybatis.mybatis.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse


eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.49:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      payment:
        read-timeout: 30000


#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      mybatis: TRACE
